[package]
name = "prc-rs"
version = "0.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

[lib]
name = "prc"
path = "src/lib/lib.rs"

[[bin]]
name = "param-xml"
path = "src/param-xml/main.rs"
required-features = ["param-xml"]

[features]
default = [ "param-xml" ]
param-xml = [ "quick-xml" ]

[dependencies]
byteorder = "^1.3"
hash40 = "^0.4.0"
indexmap = "^1.2"
serde = { version = "^1", features = ["derive"] }
strum = "^0.18"
strum_macros = "^0.18"
quick-xml = { version = "^0.18.1", optional = true }