[package]
name = "prc-rs"
version = "0.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
byteorder = "1.3.2"
nom = "5.0.0"
serde = "1.0.98"