[package]
name = "prc-rs"
version = "0.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

[lib]
name = "prc"
path = "src/lib.rs"

[[bin]]
name = "prc-tst"
path = "src/main.rs"

[dependencies]
byteorder = "^1.3"
hash40 = "^0.4.0"
serde = { version = "^1", features = ["derive"] }
strum = "^0.18"
strum_macros = "^0.18"
indexmap = "^1.2"
