[package]
name = "prc-rs"
version = "0.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

[lib]
name = "prc"
path = "src/lib.rs"

[[bin]]
name = "prc-tst"
path = "src/main.rs"

[dependencies]
byteorder = "1.3.2"
hash40 = "0.4.0"
serde = { version = "1.0.98", features = ["derive"] }
indexmap = "1.2.0"
